### ISSUE TITLE
Upgrade to ORMultiMap flavoured akka-data-replication

### ISSUE THREAD

**Issue by huntc** [typesafehub/akka-contrib-extra#10]
Remove ORMultiMap from akka-data-contrib once a new akka-data-replication lib is available - should be an reasonably easy upgrade and means that we have one less dependency for our sbt plugins.

/cc @edwardcallahan

**Comment by hseeberger** [comment]
Just found out that it's not enough to remove ORMultiMap from the codebase, we also must remove the dependency on akka-data-replication.
