### ISSUE TITLE
Change reconnect API

### ISSUE THREAD

**Issue by hseeberger** [typesafehub/akka-contrib-extra#23]
- `outgoingConnection` should be renamed `bindAndHandle`
- `Http.reconnect` is too much magic => instead renamve `ReconnectingStreamHttp` to `ReconnectingHttp`

/cc @ktoso

**Comment by ktoso** [comment]
> outgoingConnection should be renamed bindAndHandle
Disagree - `bind...` is used specifically for server-side, not the client side.

> Http.reconnect is too much magic => instead renamve ReconnectingStreamHttp to ReconnectingHttp
I thought you liked it [during review](https://github.com/typesafehub/akka-contrib-extra/pull/22#discussion_r26003346) ;-) No strong feelings on this one, can be removed. The `ReconnectingHttp` name sounds good, Tcp should be `ReconnectingStreamTcp` though, as the "normal one" is `StreamTcp`.

Do you want to do the changes?

**Comment by hseeberger** [comment]
> Do you want to do the changes?

Not yet, I just wanted to start a discussion.

Indeed, `bindAndHandle` is no good, but as there's the "handler" parameter, the method is definitely providing more than just a connection. Maybe `connectAndHandle`?

**Comment by ktoso** [comment]
Passing in the `handler` flow is too limiting, it must be the `onConnection` callback style IMO (because you may need to get materialized values out for each materialization - e.g. my use case).
Maybe something that points out that this may be multiple outgoing connections (for each reconnect)? How about `outgoingConnections(...)(onConnection = ...)`?

**Comment by hseeberger** [comment]
With handler I mean `onConnect`, were on the same page here. The issue I have with `outgoingConnection` (or the plural) is that it sounds too "less", the method does more that just return a connection, it applies the given `onConnect` handler. Maybe `withOutgoingConnection`?

**Comment by ktoso** [comment]
Removed reconnect utilities from contrail, they are not something we want to provide as such (at this level), see https://github.com/typesafehub/akka-contrib-extra/issues/30 and related tickets in akka for details.

**Comment by ktoso** [comment]
Can't close issues on this repo, please close this.
