### ISSUE TITLE
Remove reconnection facilities

### ISSUE THREAD

**Issue by ktoso** [typesafehub/akka-contrib-extra#30]
They've proved to be "not enough", and more fancy solutions had to be implemented in projects.
In order to avoid people depending on these we should remove them.

The functionality is (a core building block for it) will be implemented in akka-streams directly.
See these tickets to track progress: https://github.com/akka/akka/issues/16985 https://github.com/akka/akka/issues/16882

**Comment by huntc** [comment]
Thanks Konrad. Could I get a PR out of you for this?

**Comment by ktoso** [comment]
yes, it's coming tomorrow :)

**Comment by huntc** [comment]
That's awesome. Thanks @ktoso

**Comment by ktoso** [comment]
Thanks for closing / merging @2m!

**Comment by ktoso** [comment]
Current recommendation: https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/Retry.scala
