### ISSUE TITLE
Missing 2.12.x artifacts

### ISSUE THREAD

**Issue by MasseGuillaume** [typesafehub/akka-contrib-extra#71]
* [X] [2.10](https://dl.bintray.com/akka-contrib-extra/maven/com/typesafe/akka/akka-contrib-extra_2.10/1.12.0/)
* [X] [2.11](https://dl.bintray.com/akka-contrib-extra/maven/com/typesafe/akka/akka-contrib-extra_2.11/1.12.0/)
* [ ] [2.12](https://dl.bintray.com/akka-contrib-extra/maven/com/typesafe/akka/akka-contrib-extra_2.12/1.12.0/)

**Comment by MasseGuillaume** [comment]
ops I was looking at the wrong repo, this is the correct one: https://dl.bintray.com/typesafe/maven-releases/com/typesafe/akka/akka-contrib-extra_2.12/4.0.0/

**Comment by MasseGuillaume** [comment]
However, some releases are missing for 2.12

https://dl.bintray.com/typesafe/maven-releases/com/typesafe/akka/akka-contrib-extra_2.11/
3.4.2/
4.0.0/
4.1.0/
4.1.1/
4.1.2/
4.1.3/

vs

https://dl.bintray.com/typesafe/maven-releases/com/typesafe/akka/akka-contrib-extra_2.12/
4.0.0/

**Comment by huntc** [comment]
I recall that we missed a few releases for 2.12. The latest releases should be there though. Is there a particular reason that you want the older releases?

**Comment by MasseGuillaume** [comment]
I don't see the latests version (4.1.3) for 2.12: https://dl.bintray.com/typesafe/maven-releases/com/typesafe/akka/akka-contrib-extra_2.12/4.1.3/

**Comment by huntc** [comment]
@longshorej Any chance you can publish? I no longer have rights...

**Comment by longshorej** [comment]
Oops - sorry about that! `4.1.3` is now published for `2.12`.

**Comment by huntc** [comment]
Thanks!

**Comment by MasseGuillaume** [comment]
Awesome, thanks!

```scala
scalaVersion := "2.12.3"
resolvers += Resolver.typesafeRepo("releases")
libraryDependencies += "com.typesafe.akka" %% "akka-contrib-extra" % "4.1.3"
```
